// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/location/location.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetCourierLatestPositionRequest struct {
	CourierId            string   `protobuf:"bytes,1,opt,name=courier_id,json=courierId,proto3" json:"courier_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCourierLatestPositionRequest) Reset()         { *m = GetCourierLatestPositionRequest{} }
func (m *GetCourierLatestPositionRequest) String() string { return proto.CompactTextString(m) }
func (*GetCourierLatestPositionRequest) ProtoMessage()    {}
func (*GetCourierLatestPositionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b346e182376f6a61, []int{0}
}

func (m *GetCourierLatestPositionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCourierLatestPositionRequest.Unmarshal(m, b)
}
func (m *GetCourierLatestPositionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCourierLatestPositionRequest.Marshal(b, m, deterministic)
}
func (m *GetCourierLatestPositionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCourierLatestPositionRequest.Merge(m, src)
}
func (m *GetCourierLatestPositionRequest) XXX_Size() int {
	return xxx_messageInfo_GetCourierLatestPositionRequest.Size(m)
}
func (m *GetCourierLatestPositionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCourierLatestPositionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCourierLatestPositionRequest proto.InternalMessageInfo

func (m *GetCourierLatestPositionRequest) GetCourierId() string {
	if m != nil {
		return m.CourierId
	}
	return ""
}

type GetCourierLatestPositionResponse struct {
	CourierId            string               `protobuf:"bytes,1,opt,name=courier_id,json=courierId,proto3" json:"courier_id,omitempty"`
	Latitude             float64              `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64              `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetCourierLatestPositionResponse) Reset()         { *m = GetCourierLatestPositionResponse{} }
func (m *GetCourierLatestPositionResponse) String() string { return proto.CompactTextString(m) }
func (*GetCourierLatestPositionResponse) ProtoMessage()    {}
func (*GetCourierLatestPositionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b346e182376f6a61, []int{1}
}

func (m *GetCourierLatestPositionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCourierLatestPositionResponse.Unmarshal(m, b)
}
func (m *GetCourierLatestPositionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCourierLatestPositionResponse.Marshal(b, m, deterministic)
}
func (m *GetCourierLatestPositionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCourierLatestPositionResponse.Merge(m, src)
}
func (m *GetCourierLatestPositionResponse) XXX_Size() int {
	return xxx_messageInfo_GetCourierLatestPositionResponse.Size(m)
}
func (m *GetCourierLatestPositionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCourierLatestPositionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCourierLatestPositionResponse proto.InternalMessageInfo

func (m *GetCourierLatestPositionResponse) GetCourierId() string {
	if m != nil {
		return m.CourierId
	}
	return ""
}

func (m *GetCourierLatestPositionResponse) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *GetCourierLatestPositionResponse) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *GetCourierLatestPositionResponse) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func init() {
	proto.RegisterType((*GetCourierLatestPositionRequest)(nil), "GetCourierLatestPositionRequest")
	proto.RegisterType((*GetCourierLatestPositionResponse)(nil), "GetCourierLatestPositionResponse")
}

func init() { proto.RegisterFile("proto/location/location.proto", fileDescriptor_b346e182376f6a61) }

var fileDescriptor_b346e182376f6a61 = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0x8d, 0x2e, 0x6a, 0xc7, 0x5b, 0x10, 0x29, 0xc5, 0x65, 0x63, 0x4f, 0x3d, 0xa5, 0xb8,
	0x7e, 0x01, 0xd1, 0x83, 0x08, 0x1e, 0xa4, 0x78, 0xf2, 0x22, 0xd9, 0xed, 0x58, 0x02, 0xd9, 0x4e,
	0x6d, 0xa6, 0x7e, 0x29, 0xbf, 0xa4, 0x6c, 0xb2, 0x7f, 0x4e, 0xa5, 0xb7, 0xcc, 0x7b, 0xc3, 0xe3,
	0xfd, 0x32, 0x30, 0xef, 0x7a, 0x62, 0x2a, 0x1d, 0xad, 0x0d, 0x5b, 0x6a, 0x0f, 0x0f, 0x1d, 0xf4,
	0x6c, 0xd1, 0x10, 0x35, 0x0e, 0xcb, 0x30, 0xad, 0x86, 0xef, 0x92, 0xed, 0x06, 0x3d, 0x9b, 0x4d,
	0x17, 0x17, 0xf2, 0x47, 0x58, 0xbc, 0x20, 0x3f, 0xd3, 0xd0, 0x5b, 0xec, 0xdf, 0x0c, 0xa3, 0xe7,
	0x77, 0xf2, 0x76, 0x1b, 0x51, 0xe1, 0xcf, 0x80, 0x9e, 0xe5, 0x1c, 0x60, 0x1d, 0xfd, 0x2f, 0x5b,
	0xa7, 0x42, 0x89, 0x22, 0xa9, 0x92, 0x9d, 0xf2, 0x5a, 0xe7, 0x7f, 0x02, 0xd4, 0x78, 0x84, 0xef,
	0xa8, 0xf5, 0x38, 0x91, 0x21, 0x33, 0xb8, 0x74, 0x86, 0x2d, 0x0f, 0x35, 0xa6, 0xa7, 0x4a, 0x14,
	0xa2, 0x3a, 0xcc, 0xf2, 0x16, 0x12, 0x47, 0x6d, 0x13, 0xcd, 0xb3, 0x60, 0x1e, 0x05, 0xa9, 0x61,
	0xb6, 0x45, 0x4a, 0x67, 0x4a, 0x14, 0x57, 0xcb, 0x4c, 0x47, 0x5e, 0xbd, 0xe7, 0xd5, 0x1f, 0x7b,
	0xde, 0x2a, 0xec, 0x2d, 0x1d, 0x5c, 0xec, 0x9a, 0x4a, 0x03, 0xe9, 0x58, 0x6f, 0xa9, 0xf4, 0xc4,
	0xaf, 0x64, 0x77, 0x7a, 0x0a, 0x3a, 0x3f, 0x79, 0xba, 0xf9, 0xbc, 0x6e, 0xb0, 0xc5, 0xde, 0x30,
	0x1e, 0x4f, 0xf4, 0x7b, 0xbf, 0x3a, 0x0f, 0xfd, 0x1e, 0xfe, 0x03, 0x00, 0x00, 0xff, 0xff, 0xd6,
	0x54, 0x30, 0x79, 0xbe, 0x01, 0x00, 0x00,
}
